flowchart BT
    A{{Title}}

    subgraph Group1
        A1[Item 1 in Group 1]
        A2[Item 2 in Group 1]
    end

    subgraph Group2
        B1[Item 1 in Group 2]
        B2[Item 2 in Group 2]
    end

    Group1 --> A
    B1 --> A2

    style A fill:#4CAF50,stroke:#333,stroke-width:2px,color:#fff
    style B2 fill:#4CAF50,stroke:#333,stroke-width:2px,color:#fff
    