title: Simple Project Tool
description: >
  A tool to convert YAML data into a Mermaid flowchart representing project stages and milestones.
  Other functionality may be added in the future, next up is outputting a suggested order of stages.
parallel_stages:
  - title: Show completion of stages
    milestone: true
    complete: true
    description: >
      Display the completion status of each stage in the project by colouring
      stages green if they themselves or any parent node is marked as complete.
    stages:
      - title: Show every stage (including completed) (completion of stages)
        description: >
          Display every stage in the project, regardless of completion status.
          This is useful for understanding the project structure.
        complete: true
      - title: Show incomplete stages only (completion of stages)
        description: >
          Display only the stages that are not marked as complete.
          This helps focus on the work that still needs to be done.
        complete: true
stages:
  - title: Suggest order of stages
    description: Provide a suggested order of work based on the topological sort and dependencies
    depends_on:
      - Perform topological sort
    milestone: true
    complete: true
    stages:
      - title: Give the order of work to stdout when requested
        description: Generate a list of stages in the suggested order of execution
      - title: Convert generate.py to handle command line arguments
        description: Modify the script to accept command line arguments for flexibility
  - title: YAML to Mermaid Flowchart
    milestone: true
    description: Convert YAML data describing a projects stages and milestones into a Mermaid flowchart
    parallel_stages:
      - title: Parse YAML
        description: Read and parse the YAML data to extract stages and milestones
        milestone: true
        complete: true
        stages:
          - title: Define YAML Syntax
            description: Define the structure of the YAML data to be parsed
            stages:
              - title: Identify key elements
                description: Determine the key elements that need to be included in the YAML structure
              - title: Create YAML schema
                description: Draft a schema that outlines the expected format of the YAML data
              - title: Validate YAML schema
                description: Ensure the schema is correct and can be used to validate YAML files
          - title: Read YAML File
            description: Load the YAML file containing project data
            stages:
              - title: Discover a parser library
                description: Find a suitable library to parse YAML files
                stages:
                  - title: Research YAML parsers
                    description: Look for libraries that can parse YAML in the chosen programming language
                  - title: Select a parser library
                    description: Choose a library based on features, performance, and ease of use
                  - title: Test the parser library
                    description: Run tests to ensure the selected library works correctly with sample YAML files
              - title: Install the parser library
                description: Install the selected YAML parser library in the project environment
      - title: Perform topological sort
        description: Sort the stages and milestones in a topological order to prepare for flowchart generation
        depends_on:
          - Parse YAML
        milestone: true
        complete: true

      - title: Generate Mermaid Syntax
        description: Convert the parsed data into Mermaid flowchart syntax
        milestone: true
        complete: true
        stages:
          - title: Define Mermaid Syntax
            description: Outline the structure of the Mermaid flowchart syntax to be generated
            stages:
              - title: Identify flowchart elements
                description: Determine the key elements that need to be represented in the flowchart
              - title: Document Mermaid schema
                description: Draft a schema that outlines the expected format of the Mermaid flowchart
          - title: Generate Flowchart Syntax
            depends_on:
              - Parse YAML
            description: Convert the parsed YAML data into Mermaid flowchart syntax
            stages:
              - title: Map YAML data to Mermaid syntax
                description: Create a mapping from YAML elements to Mermaid flowchart elements
              - title: Generate final Mermaid code
                description: Produce the final Mermaid code based on the mapped data
