title: YAML to Mermaid Flowchart
description: Convert YAML data describing a projects stages and milestones into a Mermaid flowchart
parallel_stages:
  - title: Parse YAML
    description: Read and parse the YAML data to extract stages and milestones
    milestone: true
    complete: true
    stages:
      - title: Define YAML Syntax
        description: Define the structure of the YAML data to be parsed
        stages:
          - title: Identify key elements
            description: Determine the key elements that need to be included in the YAML structure
          - title: Create YAML schema
            description: Draft a schema that outlines the expected format of the YAML data
          - title: Validate YAML schema
            description: Ensure the schema is correct and can be used to validate YAML files
      - title: Read YAML File
        description: Load the YAML file containing project data
        stages:
          - title: Discover a parser library
            description: Find a suitable library to parse YAML files
            stages:
              - title: Research YAML parsers
                description: Look for libraries that can parse YAML in the chosen programming language
              - title: Select a parser library
                description: Choose a library based on features, performance, and ease of use
              - title: Test the parser library
                description: Run tests to ensure the selected library works correctly with sample YAML files
          - title: Install the parser library
            description: Install the selected YAML parser library in the project environment
  - title: Perform topological sort
    description: Sort the stages and milestones in a topological order to prepare for flowchart generation
    depends_on:
      - Parse YAML
    milestone: true

  - title: Generate Mermaid Syntax
    description: Convert the parsed data into Mermaid flowchart syntax
    milestone: true
    stages:
      - title: Define Mermaid Syntax
        description: Outline the structure of the Mermaid flowchart syntax to be generated
        stages:
          - title: Identify flowchart elements
            description: Determine the key elements that need to be represented in the flowchart
          - title: Document Mermaid schema
            description: Draft a schema that outlines the expected format of the Mermaid flowchart
      - title: Generate Flowchart Syntax
        depends_on:
          - Parse YAML
        description: Convert the parsed YAML data into Mermaid flowchart syntax
        stages:
          - title: Map YAML data to Mermaid syntax
            description: Create a mapping from YAML elements to Mermaid flowchart elements
          - title: Generate final Mermaid code
            description: Produce the final Mermaid code based on the mapped data
